name: Deploy Web

on:
  workflow_run:
    workflows:
      - "Build and Push Web"
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-web:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Dokploy Web Deployment
        run: |
          curl --request GET '${{ secrets.DOKPLOY_WEB_WEBHOOK_URL }}'
