name: Deploy Web

on:
  workflow_run:
    workflows:
      - "Build and Push Web"
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-web:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Dokploy Web Deployment
        run: |
          curl --request POST \
            '${{ secrets.DOKPLOY_URL }}/api/application.deploy' \
            --header 'accept: application/json' \
            --header 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
            --header 'Content-Type: application/json' \
            --data '{"applicationId": "${{ secrets.DOKPLOY_WEB_APPLICATION_ID }}"}'

    # - name: Trigger Dokploy Web Deployment via webhook (Only for GitHub provider configured)
    #   run: |
    #     curl --request GET '${{ secrets.DOKPLOY_WEB_WEBHOOK_URL }}'
